# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 01:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('sub_heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('styling', wagtail.wagtailcore.blocks.StructBlock((('container_id', wagtail.wagtailcore.blocks.CharBlock(label="Container's ID", required=False)), ('container_css', wagtail.wagtailcore.blocks.CharBlock(label="Container's CSS", required=False)), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)))), required=False))))),)),
        ),
    ]
