# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 07:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171006_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='heading',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='sub_heading',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
