# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171004_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegalleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pagegalleryimage',
            name='caption',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
