# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 07:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171211_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='heading',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='sub_heading',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
